services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:18-alpine
    container_name: bitcommerce-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bitcommerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-bcp
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:root@postgres:5432/bitcommerce?schema=public"
      PORT: 3000
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend-network
    command: sh -c "npx prisma migrate deploy && npm run dev"

# Volúmenes para persistir datos
volumes:
  postgres_data:

# Red para comunicación entre contenedores
networks:
  backend-network:
    driver: bridge